services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: autoone
      MYSQL_USER: autoone
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
