@php
    $isRtl = app()->getLocale() === 'ar';
    $dir = $isRtl ? 'rtl' : 'ltr';
    $alignRight = $isRtl ? 'text-align:right;' : '';
    $font = 'DejaVu Sans'; // DejaVu covers Arabic and Latin
    $unitLabel = ['hour'=>'Hour','day'=>'Day','week'=>'Week','month'=>'Month','year'=>'Year'][$unit] ?? $unit;
@endphp
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ $dir }}">
<head>
  <meta charset="utf-8">
  <style>
    @page { margin: 36pt; }
    body { font-family: "{{ $font }}", sans-serif; font-size: 12pt; color:#111; }
    h1 { font-size: 20pt; margin: 0 0 6pt 0; }
    h2 { font-size: 14pt; margin: 18pt 0 8pt 0; }
    .muted { color:#666; }
    .row { display: flex; justify-content: space-between; margin: 6pt 0; }
    .box { border:1px solid #ccc; border-radius:6pt; padding:10pt; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border:1px solid #ddd; padding:8pt; }
  </style>
</head>
<body>

  <h1 style="{{ $alignRight }}">AutoOne Rental Contract</h1>
  <div class="muted" style="{{ $alignRight }}">Contract #{{ $booking->id }}</div>

  <h2 style="{{ $alignRight }}">Parties</h2>
  <div class="box">
    <div class="row"><strong>Customer:</strong> <span>{{ $user->name }} ({{ $user->email }})</span></div>
    <div class="row"><strong>Provider:</strong> <span>{{ $rental->title }} — {{ $rental->provider_type }}</span></div>
    <div class="row"><strong>Location:</strong> <span>{{ $rental->location_city ?? $rental->location }}</span></div>
  </div>

  <h2 style="{{ $alignRight }}">Booking</h2>
  <table>
    <tr>
      <th>Start</th><th>End</th><th>Unit</th><th>Qty</th><th>Unit Price</th><th>Total</th>
    </tr>
    <tr>
      <td>{{ $booking->start_date->format('Y-m-d H:i') }}</td>
      <td>{{ $booking->end_date->format('Y-m-d H:i') }}</td>
      <td>{{ $unitLabel }}</td>
      <td>{{ $qty }}</td>
      <td>€{{ number_format($unitPrice, 2) }}</td>
      <td><strong>€{{ number_format($booking->total_price, 2) }}</strong></td>
    </tr>
  </table>

  @if($booking->notes)
    <h2 style="{{ $alignRight }}">Notes</h2>
    <div class="box">{{ $booking->notes }}</div>
  @endif

  <p class="muted" style="margin-top:24pt; {{ $alignRight }}">
    Generated by AutoOne · {{ now()->format('Y-m-d H:i') }}
  </p>

</body>
</html>
